In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("train.csv")
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [ ]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [ ]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [ ]:
data = data[['GrLivArea', 'BedroomAbvGr', 'FullBath', 'SalePrice']]

KeyError: "None of [Index(['GrLivArea', 'BedroomAbvGr', 'FullBath', 'SalePrice'], dtype='str')] are in the [columns]"

In [ ]:
data = data.dropna()

In [ ]:
X = data[['GrLivArea', 'BedroomAbvGr', 'FullBath']]
y = data['SalePrice']

KeyError: "None of [Index(['GrLivArea', 'BedroomAbvGr', 'FullBath'], dtype='str')] are in the [columns]"

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

NameError: name 'X' is not defined

In [ ]:
data.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='str')

In [ ]:
data = data[['RM', 'LSTAT', 'PTRATIO', 'MEDV']]

In [ ]:
data = data.dropna()

In [ ]:
X = data[['RM', 'LSTAT', 'PTRATIO']]
y = data['MEDV']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
predictions = model.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score

r2_score(y_test, predictions)

0.7380852088423927

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(y_test, predictions)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted House Prices")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
!pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.9-cp311-cp311-win_amd64.whl.metadata (52 kB)
     ---------------------------------------- 0.0/52.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     -------------- ----------------------- 20.5/52.8 kB 162.5 kB/s eta 0:00:01
     ----------------------------- -------- 41.0/52.8 kB 279.3 kB/s eta 0:00:01
     -------------------------------------- 52.8/52.8 kB 302.1 kB/s eta 0:00:00
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp311-cp311-win_amd64.whl.metadata (119 kB)
     ---------------------------------------- 0.0/119.8 kB ? eta -:--:--
     ------------------------------ -------- 92.2/119.8 kB 2.6 MB/s eta 0:00:01
     ----------------------------------- -- 112.6/119.8 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 119.8/119.8 kB 1.2 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp311-cp311-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\rishi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\rishi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (26.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp311-cp311-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rishi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\rishi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.9-cp311-cp311-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.1/8.2 MB 2.6 MB/s eta 0:00:04
   ---------------------------------------- 0.1/8.2 MB 2.6 MB/s eta 0:00:04
    --------------------------------------- 0.2/8.2 MB 1.4 MB/s eta 0:00:06
    --------------------------------------- 0.2/8.2 MB 1.4 MB/s eta 0:00:06
    --------------------------------------- 0.2/8.2 MB 1.4 MB/s eta 0:00:06
   - -------------------------------------- 0.3/8.2 MB 1.2 MB/s eta 0:00:07
   - -------------------------------------- 0.3/8.2 MB 1.2 MB/s eta 0:00:07
   - -------------------------------------- 0.3/8.2 MB 863.3 kB/s eta 0:00:10
   - -------------------------------------- 0.4/8.2 MB 1.0 MB/s eta 0:00:08
   - -------------------------------------- 0.4/8.2 MB 1.0 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/8.2 MB 1.0 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/8.2 MB 1.0 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/8.2 MB 1.0 MB/s eta 0:00:08
   --- ------------------------------------ 0.6/8.2 MB 1.0 MB/s eta 0:00:08
   --- ------------------------------------ 0.6/8.2 MB 1.0 MB/s eta 0:00:08
   --- ------------------------------------ 0.6/8.2 MB 1.0 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/8.2 MB 1.1 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/8.2 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 0.8/8.2 MB 989.4 kB/s eta 0:00:08
   ---- ----------------------------------- 0.9/8.2 MB 1.0 MB/s eta 0:00:07
   ---- ----------------------------------- 0.9/8.2 MB 1.0 MB/s eta 0:00:07
   ---- ----------------------------------- 1.0/8.2 MB 1.0 MB/s eta 0:00:08
   ----- ---------------------------------- 1.1/8.2 MB 1.1 MB/s eta 0:00:07
   ----- ---------------------------------- 1.1/8.2 MB 1.1 MB/s eta 0:00:07
   ------ --------------------------------- 1.2/8.2 MB 1.1 MB/s eta 0:00:07
   ------ --------------------------------- 1.2/8.2 MB 1.1 MB/s eta 0:00:07
   ------ --------------------------------- 1.2/8.2 MB 1.1 MB/s eta 0:00:07
   ------ --------------------------------- 1.4/8.2 MB 1.1 MB/s eta 0:00:07
   ------ --------------------------------- 1.4/8.2 MB 1.1 MB/s eta 0:00:07
   ------- -------------------------------- 1.5/8.2 MB 1.1 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.2 MB 1.2 MB/s eta 0:00:06
   ------- -------------------------------- 1.6/8.2 MB 1.2 MB/s eta 0:00:06
   -------- ------------------------------- 1.7/8.2 MB 1.1 MB/s eta 0:00:06
   -------- ------------------------------- 1.8/8.2 MB 1.2 MB/s eta 0:00:06
   -------- ------------------------------- 1.8/8.2 MB 1.2 MB/s eta 0:00:06
   --------- ------------------------------ 1.9/8.2 MB 1.2 MB/s eta 0:00:06
   --------- ------------------------------ 1.9/8.2 MB 1.2 MB/s eta 0:00:06
   --------- ------------------------------ 2.0/8.2 MB 1.2 MB/s eta 0:00:06
   ---------- ----------------------------- 2.1/8.2 MB 1.2 MB/s eta 0:00:05
   ---------- ----------------------------- 2.2/8.2 MB 1.2 MB/s eta 0:00:05
   ---------- ----------------------------- 2.2/8.2 MB 1.2 MB/s eta 0:00:05
   ----------- ---------------------------- 2.4/8.2 MB 1.3 MB/s eta 0:00:05
   ------------ --------------------------- 2.5/8.2 MB 1.3 MB/s eta 0:00:05
   ------------ --------------------------- 2.6/8.2 MB 1.3 MB/s eta 0:00:05
   ------------- -------------------------- 2.7/8.2 MB 1.4 MB/s eta 0:00:05
   ------------- -------------------------- 2.8/8.2 MB 1.4 MB/s eta 0:00:05
   -------------- ------------------------- 3.0/8.2 MB 1.4 MB/s eta 0:00:04
   -------------- ------------------------- 3.1/8.2 MB 1.4 MB/s eta 0:00:04
   --------------- ------------------------ 3.2/8.2 MB 1.5 MB/s eta 0:00:04
   ---------------- ----------------------- 3.3/8.2 MB 1.5 MB/s eta 0:00:04
   ---------------- ----------------------- 3.5/8.2 MB 1.5 MB/s eta 0:00:04
   ----------------- ---------------------- 3.6/8.2 MB 1.6 MB/s eta 0:00:03
   ------------------ --------------------- 3.9/8.2 MB 1.6 MB/s eta 0:00:03
   ------------------- -------------------- 4.0/8.2 MB 1.7 MB/s eta 0:00:03
   -------------------- ------------------- 4.1/8.2 MB 1.7 MB/s eta 0:00:03
   -------------------- ------------------- 4.1/8.2 MB 1.7 MB/s eta 0:00:03
   --------------------- ------------------ 4.3/8.2 MB 1.7 MB/s eta 0:00:03
   --------------------- ------------------ 4.4/8.2 MB 1.7 MB/s eta 0:00:03
   ---------------------- ----------------- 4.6/8.2 MB 1.7 MB/s eta 0:00:03
   ----------------------- ---------------- 4.8/8.2 MB 1.8 MB/s eta 0:00:02
   ----------------------- ---------------- 4.9/8.2 MB 1.8 MB/s eta 0:00:02
   ------------------------ --------------- 5.1/8.2 MB 1.8 MB/s eta 0:00:02
   ------------------------- -------------- 5.3/8.2 MB 1.9 MB/s eta 0:00:02
   -------------------------- ------------- 5.5/8.2 MB 1.9 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.2 MB 2.0 MB/s eta 0:00:02
   ----------------------------- ---------- 6.1/8.2 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 6.2/8.2 MB 2.1 MB/s eta 0:00:01
   ------------------------------- -------- 6.4/8.2 MB 2.1 MB/s eta 0:00:01
   ------------------------------- -------- 6.5/8.2 MB 2.1 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.2 MB 2.1 MB/s eta 0:00:01
   --------------------------------- ------ 6.9/8.2 MB 2.2 MB/s eta 0:00:01
   ---------------------------------- ----- 7.0/8.2 MB 2.2 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 7.4/8.2 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 7.5/8.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 7.7/8.2 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  8.0/8.2 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 2.3 MB/s eta 0:00:00
Downloading contourpy-1.3.3-cp311-cp311-win_amd64.whl (225 kB)
   ---------------------------------------- 0.0/225.2 kB ? eta -:--:--
   ------------------------------ --------- 174.1/225.2 kB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 225.2/225.2 kB 4.6 MB/s eta 0:00:00
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp311-cp311-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   --- ------------------------------------ 0.2/2.3 MB 12.3 MB/s eta 0:00:01
   ----- ---------------------------------- 0.3/2.3 MB 7.0 MB/s eta 0:00:01
   --------- ------------------------------ 0.6/2.3 MB 5.3 MB/s eta 0:00:01
   ------------ --------------------------- 0.7/2.3 MB 4.2 MB/s eta 0:00:01
   --------------- ------------------------ 0.9/2.3 MB 4.4 MB/s eta 0:00:01
   ------------------- -------------------- 1.1/2.3 MB 4.3 MB/s eta 0:00:01
   ---------------------- ----------------- 1.3/2.3 MB 4.3 MB/s eta 0:00:01
   ------------------------- -------------- 1.5/2.3 MB 4.6 MB/s eta 0:00:01
   ----------------------------- ---------- 1.7/2.3 MB 4.6 MB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.3 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 2.0/2.3 MB 4.2 MB/s eta 0:00:01
   ------------------------------------- -- 2.2/2.3 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  2.3/2.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  2.3/2.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  2.3/2.3 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 3.3 MB/s eta 0:00:00
Downloading kiwisolver-1.5.0-cp311-cp311-win_amd64.whl (73 kB)
   ---------------------------------------- 0.0/73.5 kB ? eta -:--:--
   ---------------------------------------- 73.5/73.5 kB 2.0 MB/s eta 0:00:00
Downloading pillow-12.2.0-cp311-cp311-win_amd64.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/7.1 MB 3.2 MB/s eta 0:00:03
   - -------------------------------------- 0.3/7.1 MB 3.2 MB/s eta 0:00:03
   -- ------------------------------------- 0.5/7.1 MB 3.7 MB/s eta 0:00:02
   --- ------------------------------------ 0.6/7.1 MB 3.2 MB/s eta 0:00:03
   --- ------------------------------------ 0.6/7.1 MB 3.6 MB/s eta 0:00:02
   --- ------------------------------------ 0.7/7.1 MB 2.7 MB/s eta 0:00:03
   ---- ----------------------------------- 0.8/7.1 MB 3.1 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/7.1 MB 2.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.1/7.1 MB 2.9 MB/s eta 0:00:03
   ------- -------------------------------- 1.3/7.1 MB 2.9 MB/s eta 0:00:02
   -------- ------------------------------- 1.5/7.1 MB 3.1 MB/s eta 0:00:02
   --------- ------------------------------ 1.6/7.1 MB 3.2 MB/s eta 0:00:02
   ---------- ----------------------------- 1.8/7.1 MB 3.2 MB/s eta 0:00:02
   ---------- ----------------------------- 1.9/7.1 MB 3.1 MB/s eta 0:00:02
   ----------- ---------------------------- 2.1/7.1 MB 3.2 MB/s eta 0:00:02
   ------------ --------------------------- 2.3/7.1 MB 3.2 MB/s eta 0:00:02
   ------------- -------------------------- 2.4/7.1 MB 3.2 MB/s eta 0:00:02
   -------------- ------------------------- 2.5/7.1 MB 3.2 MB/s eta 0:00:02
   -------------- ------------------------- 2.5/7.1 MB 3.0 MB/s eta 0:00:02
   --------------- ------------------------ 2.7/7.1 MB 3.1 MB/s eta 0:00:02
   --------------- ------------------------ 2.8/7.1 MB 3.0 MB/s eta 0:00:02
   ---------------- ----------------------- 2.9/7.1 MB 3.0 MB/s eta 0:00:02
   ----------------- ---------------------- 3.0/7.1 MB 3.0 MB/s eta 0:00:02
   ------------------ --------------------- 3.3/7.1 MB 3.1 MB/s eta 0:00:02
   ------------------- -------------------- 3.4/7.1 MB 3.1 MB/s eta 0:00:02
   -------------------- ------------------- 3.6/7.1 MB 3.1 MB/s eta 0:00:02
   ---------------------- ----------------- 3.9/7.1 MB 3.2 MB/s eta 0:00:01
   ----------------------- ---------------- 4.1/7.1 MB 3.3 MB/s eta 0:00:01
   ------------------------ --------------- 4.4/7.1 MB 3.3 MB/s eta 0:00:01
   ------------------------- -------------- 4.5/7.1 MB 3.4 MB/s eta 0:00:01
   -------------------------- ------------- 4.7/7.1 MB 3.4 MB/s eta 0:00:01
   --------------------------- ------------ 4.9/7.1 MB 3.4 MB/s eta 0:00:01
   ---------------------------- ----------- 5.1/7.1 MB 3.5 MB/s eta 0:00:01
   ----------------------------- ---------- 5.2/7.1 MB 3.5 MB/s eta 0:00:01
   ------------------------------ --------- 5.3/7.1 MB 3.4 MB/s eta 0:00:01
   ------------------------------- -------- 5.6/7.1 MB 3.4 MB/s eta 0:00:01
   -------------------------------- ------- 5.7/7.1 MB 3.4 MB/s eta 0:00:01
   --------------------------------- ------ 5.9/7.1 MB 3.5 MB/s eta 0:00:01
   ---------------------------------- ----- 6.1/7.1 MB 3.5 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.1 MB 3.5 MB/s eta 0:00:01
   ------------------------------------ --- 6.5/7.1 MB 3.6 MB/s eta 0:00:01
   -------------------------------------- - 6.7/7.1 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  6.9/7.1 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  6.9/7.1 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  6.9/7.1 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.1 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.1 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 7.1/7.1 MB 3.4 MB/s eta 0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
   ---------------------------------------- 0.0/122.8 kB ? eta -:--:--
   ---------------------------------------- 122.8/122.8 kB 7.5 MB/s eta 0:00:00
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.9 pillow-12.2.0 pyparsing-3.3.2

[notice] A new release of pip is available: 24.0 -> 26.1
[notice] To update, run: C:\Users\rishi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip